name: realtime_talk
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # design
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # media
  record: ^5.0.4

  # other
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.18.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
