name: recorod_to_text
description: "record data to text"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # design
  flutter_riverpod: ^2.5.1

  # record
  record: ^5.1.2

  # network  
  dio: ^5.6.0

  # localstorage
  shared_preferences: ^2.3.2
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

  # other
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
