name: recorod_to_text
description: "record data to text"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: ^2.4.10
  record: ^5.0.4
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
